### ISSUE TITLE
Error: No user with the name '...' was found, even if the user exists

### ISSUE THREAD

**Issue by Exhabition** [Richienb/minecraft-player#1]
**Describe the bug**
Returns Error: No user with the name '...' was found
... being a name of user

**To Reproduce**

1. Ask information like so: minecraftPlayer(playerName).then(async (player)...
2. Most of the users exist, but sometimes users don't 'exist' while they clearly do, for example "Sapnap"

**Expected behavior**
The player info of "Sapnap"

**Screenshots**
![image](https://user-images.githubusercontent.com/63742759/105091281-e6002080-5a9f-11eb-937a-a7fe1807dffc.png)

**Additional context**
Sites like NameMC show that "Sapnap" actually exist

**Comment by Exhabition** [comment]
https://api.ashcon.app/mojang/v2/user/sapnap also exists here

<blockquote></blockquote>

**Comment by Richienb** [comment]
The error message you got was returned by the API itself - it was not actually generated by the module:

https://github.com/Richienb/minecraft-player/blob/c01a4c81801816af13d7201bb2490ec8368e184f/index.js#L24

Can you provide a reproducible example?

**Comment by Exhabition** [comment]
I know, that's why I thought it was weird, I tested it again today, and it seems to work perfectly fine now.

I tested for the users "sapnap" & "dhddraws", the last person notified me of this issue and I indeed found the errors messages in my logs. I am not sure why this happend. Do you have any ideas on why the API returned that error?

**Comment by Richienb** [comment]
https://github.com/Electroid/mojang-api/issues/35
